name: nutribuddy.ai
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  image_picker: ^0.8.0
  flutter:
    sdk: flutter
  flutter_local_notifications: 15.1.0+1
  # ... other dependencies ...
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/water_droplet.jpeg
    - assets/vaccine_icon.jpeg

  # ... other flutter configuration ...
